### PR TITLE
Restructure everything

### PR DESCRIPTION
**Pull request by Dinnerbone**
tldr:
- Native is now toplevel, app is nested
- UI uses Jetpack Compose and rewritten and redesigned (though not much of it, yet)
- App itself is now written in kotlin and based off the current standard Android Studio template
- ... except for the FullscreenNativeActivity. That's untouched and still java. For now.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
https://cdn.discordapp.com/attachments/1140068363532517526/1218338853044093029/Screen_recording_20240316_002324.webm?ex=66074d7a&is=65f4d87a&hm=981a02fdf5450c85eda67b733cc2bf194093c8ce1f639e8335f0c07a1d60a5d7& for new UI, such as it is

**Comment by torokati44** [comment]
> for new UI, such as it is

Am sorry, what? :face_with_spiral_eyes: May be my english not good, but not understand what you mean.

**Comment by Dinnerbone** [comment]
> > for new UI, such as it is
> 
> Am sorry, what? 😵‍💫 May be my english not good, but not understand what you mean.

"This is an example of the new UI. It isn't very much."

**Comment by torokati44** [comment]
>    Native is now toplevel, app is nested

I'm okay with that - just wondering, is the reason for this logical, or technical, or arbitrary...? I would have expected the opposite to be more the more straightforward.
>    UI uses Jetpack Compose and rewritten and redesigned (though not much of it, yet)

*whoosh sounds*

>    App itself is now written in kotlin and based off the current standard Android Studio template

yay, modern languages!

>    ... except for the FullscreenNativeActivity. That's untouched and still java. For now.

👀

**Comment by Dinnerbone** [comment]
> I'm okay with that - just wondering, is the reason for this logical, or technical, or arbitrary...? I would have expected the opposite to be more the more straightforward.

This felt the most logical to me. This way you can `gradlew` and `cargo` from the root directory, whereas before you had to `cd` to either, and the other way around would only be `gradle` from root and `cargo` after a `cd`.

> _whoosh sounds_

You know all that xml layout stuff? It's not that. :D

**Comment by Dinnerbone** [comment]
I had to disable the "conditionally apply cargondk plugin" thing for now because I can't get that to work in modern gradle/kotlin. Gradle wants plugins statically, without conditions :(

Can revisit it for speedups later - starting with caches!

**Comment by torokati44** [comment]
Does the "Open  URL" button still work for you? :thinking:
I get a little white rectangle on a black background when trying it, and that's it.
I tried with this URL: https://z0r.de/L/z0r-de_7000.swf

**Comment by Dinnerbone** [comment]
whoops

**Review by torokati44 — APPROVED** [review]
Eh, you know what, just get it in.

I haven't looked through all the code changes (obviously), but I'm like 94.7 (+/- 0.2) percent sure this will be a net improvement anyway.

**Pull request merged**
