### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by Dinnerbone**

### CODE REVIEW

**Review by torokati44 — APPROVED** [review]
The worst thing could be that the :robot: makes some nonsense PRs. Or doesn't ... any kind at all.

**Comment by Dinnerbone** [comment]
It'll make at least one PR that we'll need to mark as ignore after it makes it, but otherwise we'll see!

**Comment by torokati44** [comment]
> It'll make at least one PR that we'll need to mark as ignore after it makes it

Uuuhm. Okay, but please elaborate? :D

**Comment by Dinnerbone** [comment]
The android-activity crate depends on the really old version of game-activity being used in gradle

**Comment by torokati44** [comment]
Oh, of course, I haven't seen that being explicitly dealt with in the config itself.

**Comment by torokati44** [comment]
Kinda hidden-state-y, but oh well, I don't mind.

**Pull request merged**
