### PR TITLE
do the dinghy thingy

### PR DESCRIPTION
**Pull request by torokati44**

### CODE REVIEW

**Comment by torokati44** [comment]
huh, it no work. weird.

**Comment by torokati44** [comment]
Ah, good point, silly me, thanks!

**Comment by torokati44** [comment]
Tried it without KVM, same thing:
```
  Disabling Linux hardware acceleration.
  Starting emulator.
  /usr/bin/sh -c \/usr/local/lib/android/sdk/emulator/emulator -avd test -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -accel off &
  INFO    | Storing crashdata in: /tmp/android-runner/emu-crash-34.1.19.db, detection is enabled for process: 2203
  INFO    | Android emulator version 34.1.19.0 (build_id 11525734) (CL:N/A)
  INFO    | Found systemPath /usr/local/lib/android/sdk/system-images/android-30/google_apis/arm64-v8a/
  PANIC: Avd's CPU Architecture 'arm64' is not supported by the QEMU2 emulator on x86_64 host.
  ```

**Comment by lvyitian** [comment]
ARM64 emulation on a x86_64 host currently is only possible up to API level 27 Oreo.

**Comment by torokati44** [comment]
There is probably not much point to this on an emulator, since:
 - ARM64 testing is already done by Ruffle itself in https://github.com/ruffle-rs/ruffle/pull/15029, and it belongs there.
 - Visual tests would only test SwiftShader, not a real GPU.

**Pull request closed without merging**
