### PR TITLE
Add "toggle ActionBar" to menu in FullscreenNativeActivity

### PR DESCRIPTION
**Pull request by yakagami**

### CODE REVIEW

**Comment by yakagami** [comment]
I'm not sure what is wrong with the indenting but hopefully that can be fixed later?

**Comment by torokati44** [comment]
Thank you for the PR, I hope I can get back to it soon-ish!

**Comment by yakagami** [comment]
Superseded by #77 .

**Comment by torokati44** [comment]
Welp, I didn't manage to find the time for this in time... :/ Sorry about that!

**Pull request closed without merging**
