### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by neighbor-bear**
Added Chinese translation to the homepage

### CODE REVIEW

**Comment by torokati44** [comment]
Oh, I missed this completely until now, sorry. What do you think, @Dinnerbone? Does this look alright from a technical perspective? Shouldn't we set up some sort of CrowdIn integration for this project as well? But even until then, can/should we accumulate translations like this, simply in-repo?

**Comment by Dinnerbone** [comment]
We should totally do Crowdin, and it should be pretty easy to configure - easier than Ruffle, I suspect, because android is fairly commonplace.

Accumulating in-repo is fine as long as we plan to move them over somehow

**Comment by torokati44** [comment]
Okay. Will figure out the migration later, if/when we set up CrowdIn.

**Review by torokati44 — APPROVED** [review]
Thank you for the contribution!

**Comment by torokati44** [comment]
Ah, I wanted to squash... How will I live with myself after this, @Dinnerbone ?! :sob:

**Pull request merged**
